import { NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/server'
import { generateSlug } from '@/lib/utils'

export async function POST(request: Request) {
  try {
    const { name, date, team1, team2, matchCount = 4 } = await request.json()

    if (!name || !date || !team1?.name || !team2?.name) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    const supabase = createServiceClient()
    const slug = generateSlug(name)

    // Create tournament
    const { data: tournament, error: tErr } = await supabase
      .from('tournaments')
      .insert({ slug, name, date })
      .select()
      .single()
    if (tErr || !tournament) throw tErr ?? new Error('Failed to create tournament')

    // Create secret (admin token auto-generated by DB default)
    const { data: secret, error: sErr } = await supabase
      .from('tournament_secrets')
      .insert({ tournament_id: tournament.id })
      .select('admin_token')
      .single()
    if (sErr || !secret) throw sErr ?? new Error('Failed to create secret')

    // Create teams
    await supabase.from('teams').insert([
      { tournament_id: tournament.id, name: team1.name, color_hex: team1.color_hex, light_hex: team1.light_hex, sort_order: 0 },
      { tournament_id: tournament.id, name: team2.name, color_hex: team2.color_hex, light_hex: team2.light_hex, sort_order: 1 },
    ])

    // Create empty matches
    const matchRows = Array.from({ length: matchCount }, (_, i) => ({
      tournament_id: tournament.id,
      label: `Match ${i + 1}`,
      sort_order: i,
    }))
    await supabase.from('matches').insert(matchRows)

    // Create bonus config
    await supabase.from('bonus_config').insert({ tournament_id: tournament.id })

    return NextResponse.json({ slug, adminToken: secret.admin_token, tournamentId: tournament.id })
  } catch (err) {
    console.error(err)
    return NextResponse.json({ error: 'Internal error' }, { status: 500 })
  }
}
